config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  devise_for :users

  root 'home#index'

  get 'pick_up/when/:place_id/:date', to: 'pick_up#dates', as: :pick_up_dates

  resources :pick_up, except:[:new] do
    new do
      get ':place_id', to: :new, as: ''
    end
  end

  get 'cart/add/:product_id',                to: 'cart#modal',      as: :cart_new_item
  post 'cart/add',                           to: 'cart#create',     as: :cart_item_sizables
  post 'cart/add',                           to: 'cart#create',     as: :cart_item_quantitables
  post 'cart/add',                           to: 'cart#create',     as: :cart_item_sizable_additionables
  post 'cart/add',                           to: 'cart#create',     as: :cart_item_splittables
  post 'cart/add',                           to: 'cart#create',     as: :cart_item_additionables
  post 'cart/calculate',                     to: 'cart#calculate',  as: :cart_item_calculate
  delete 'cart/:id',                         to: 'cart#destroy',    as: :cart_remove_item

  get '/cart/:mode/:product_id/:side/ingredients', to: 'cart#ingredients',as: :cart_product_items

  controller :toppings do
    post 'index',       to: :index,         as: :toppings
    post 'add',         to: :add,           as: :add_topping
    post 'calculate',   to: :calculate,     as: :calulate_toppings
    post 'toppings',    to: :add_to_cart,   as: :add_toppings_to_cart
  end

  get 'cart/price',                               to: 'cart#price',    as: :cart_price
  get 'cart(/:product_id)',                       to: 'cart#index',    as: :cart
  post 'cart/mode',                               to: 'cart#mode',     as: :cart_mode
  get 'cart/:mode/:side/:category_id(/:size_id)', to: 'cart#carousel', as: :cart_carousel

  get 'checkout_modal', to: 'checkout#modal', as: :checkout_modal

  resources :orders, only: [:create, :destroy, :show]
  get 'checkout/:code',        to: 'orders#index',   as: :checkout
  get 'orders/:code/update',   to: 'orders#update',  as: :order_update
  get 'orders/:code/print',    to: 'orders#print',   as: :order_print
  get 'checkout/:code/success',to: 'orders#success', as: :order_success
  match 'checkout/confirm',    to: 'orders#confirm', as: :checkout_confirm, via: [:get, :post]

  controller :home do
    get 'shopping',          to: :shopping,     as: :shopping
    get 'contact',           to: :contact,      as: :contact
    post 'contact',          to: :send_message, as: :send_message
    get 'about',             to: :about,        as: :about
    get 'menu(/:active)',    to: :menu,         as: :menu
    get 'order/product/:id', to: :product,      as: :product
    get 'privacy',           to: :privacy,      as: :privacy
    get 'terms',             to: :terms,        as: :terms
    get 'returns',           to: :returns,      as: :returns
  end

  namespace :admin do

    root 'home#index'
    get 'home',    to: 'home#index',   as: :home
    get 'sign_in', to: 'home#sign_in', as: :sign_in

    resources :sizes
    resources :categories
    resources :product_types
    resources :users
    resources :customers
    resources :chefs
    resources :oven_time
    resources :orders, except: [:new, :create, :edit]
    
    get 'live/customer', to:'orders#live_customer', as: :order_live_customer
    get 'live(/:place_id)/:live_type', to:'orders#live', as: :order_live
    get 'order/:id/change_order_status', to:'orders#change_order_status', as: :order_change_order_status

    get 'products/options', to:'products#options', as: :products_reload_options
    resources :products

    get 'products/:product_id/prices/new', to:'prices#new', as: :price_new
    resources :prices

    resources :places do
      post 'opening_hours(/:opening_hour_id)/shifts/add', to: 'shifts#new', as: :new_opening_hour_shift_add
      patch 'opening_hours/:opening_hour_id/shifts/add', to: 'shifts#new', as: :opening_hour_shift_add
      resources :opening_hours do
        resources :shifts, only: [:destroy, :index]
      end
    end
  end
end

app/models/place.rb
class Place < ActiveRecord::Base
  include Auditable

  has_many :opening_hours,
           dependent: :destroy

  has_attached_file :photo,
                    styles: {large:'400x450>', medium:'300x300>', thumb:'100x100>'},
                    default_url: '/images/:style/missing.png'

  has_one :oven_time

  validates :code,
            presence: true,
            uniqueness: true

  validates :name,
            presence: true,
            length: {maximum: 30},
            uniqueness: true

  validates :address,
            presence: true,
            length: {maximum: 100},
            uniqueness: true

  validates :phone,
            presence: true,
            length: {maximum: 30},
            uniqueness: true

  validates :description,
            presence: true,
            length: {maximum: 100}

  validates :map,
            length: {maximum: 500},
            uniqueness: true

  validates_attachment :photo,
                       content_type: {content_type:['image/jpg', 'image/jpeg', 'image/gif', 'image/png']},
                       size: {in: 0..500.kilobytes}

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def printer_ip_s
    self.printer_ip.to_s
  end

  def dates_available
    dates = []
    day = Date.current
    while dates.length < 7 do
      opening_hour = opening_hour_of(day)
      unless opening_hour.nil?
        if opening_hour.shifts.last.end_at(day).to_i > Time.current.to_i
          dates << day
        end
      end
      day += 1.day
    end
    dates
  end

  def times_available time
    opening_hour = self.opening_hour_of time
    opening_hour.times_available time
  end

  def first_times_available
    times_available dates_available.first
  end

  def opening_hour_of_today
    opening_hour_of Date.current
  end

  def opening_hour_of day
    self.opening_hours.find{|opening_hour| opening_hour.day_of_week == day.strftime("%A")}
  end
end

app/controllers/admin/places_controller.rb
class Admin::PlacesController < Admin::BaseController

  before_action :set_places, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    respond_to do |format|
      format.html { @places = Place.order(:name) }
      format.json { @places = Place.order(:name) }
    end
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)
    respond_to do |format|
      if @place.save
        format.html { redirect_to [:admin, @place], notice: t('messages.created', model:Place.model_name.human) }
        format.json { render action: 'show', status: :created, location: @place }
      else
        format.html { render action: 'new' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to [:admin, @place], notice: t('messages.updated', model:Place.model_name.human) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    begin
      @place.destroy
      respond_to do |format|
        format.html { redirect_to admin_places_url, notice: t('messages.deleted', model:Place.model_name.human) }
        format.json { head :no_content }
      end
    rescue ActiveRecord::InvalidForeignKey => e
      flash[:error] = t 'errors.messages.delete_fail.being_used', model:@place.name
      flash[:error_details] = e
      redirect_to [:admin, @place]
    rescue ActiveRecord::StatementInvalid => e
      flash[:error] = t 'errors.messages.ops'
      flash[:error_details] = e
      redirect_to [:admin, @place]
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_places
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit :name,
                                    :enabled,
                                    :printer_name,
                                    :printer_ip,
                                    :abn,
                                    :code,
                                    :address,
                                    :phone,
                                    :description,
                                    :map,
                                    :photo
    end
end

app/views/admin/places/_form.html.erb
<%= form_for [:admin, @place], html: {multipart:true, role:'form', style:'width:500px;'} do |f| %>

  <%= tb_show_errors_for @place %>

  <div class="checkbox <%= tb_has_error @place, :enabled %>">
    <%= f.label :enabled do %>
      <%= f.check_box :enabled %> <%= User.human_attribute_name 'enabled' %>
    <% end %>
  </div>

  <div class="form-group <%= tb_has_error @place, :photo %>">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>

  <div class="form-group <%= tb_has_error @place, :name %>">
    <%= f.label :name %>
    <%= f.text_field :name, class:'form-control' %>
  </div>

  <div class="form-group <%= tb_has_error @place, :code %>">
    <%= f.label :code %>
    <%= f.text_field :code, maxlength:3, class:'form-control' %>
  </div>

  <div class="form-group <%= tb_has_error @place, :abn %>">
    <%= f.label :abn %>
    <%= f.text_field :abn, class:'form-control' %>
  </div>

  <div class="form-group <%= tb_has_error @place, :printer_ip %>">
    <%= f.label :printer_ip %>
    <%= f.text_field :printer_ip, class:'form-control' %>
  </div>

  <div class="form-group <%= tb_has_error @place, :printer_name %>">
    <%= f.label :printer_name %>
    <%= f.text_field :printer_name, class:'form-control' %>
  </div>

  <div class="form-group <%= tb_has_error @place, :address %>">
    <%= f.label :address %>
    <%= f.text_field :address, class:'form-control' %>
  </div>

  <div class="form-group <%= tb_has_error @place, :phone %>">
    <%= f.label :phone %>
    <%= f.text_field :phone, class:'form-control phone' %>
  </div>

  <div class="form-group <%= tb_has_error @place, :description %>">
    <%= f.label :description %>
    <%= f.text_area :description, class:'form-control' %>
  </div>

  <div class="form-group <%= tb_has_error @place, :map %>">
    <%= f.label :map %>
    <%= f.text_field :map, class:'form-control' %>
  </div>

  <%= tb_submit @place %>
  <%= tb_button_back admin_places_path %>
<% end %>

app/views/admin/places/_list.html.erb
<table class="table table-condensed table-bordered">
  <thead>
    <tr>
      <th style="width:30px;"> # </th>
      <th><%= Place.human_attribute_name 'enabled' %></th>
      <th><%= Place.human_attribute_name 'name' %></th>
      <th><%= Place.human_attribute_name 'address' %></th>
      <th><%= Place.human_attribute_name 'phone' %></th>
      <th style="width:60px;"></th>
    </tr>
  </thead>
  <tbody>
    <%= render @places %>
  </tbody>
</table>

app/views/admin/places/_place.html.erb
<tr>
  <td> <%= place.id %> </td>
  <td> <%= place.enabled %> </td>
  <td> <%= place.name %> </td>
  <td> <%= place.address %> </td>
  <td> <%= place.phone %> </td>
  <td>
    <%= tb_grid_show [:admin, place] %>
    <%= tb_grid_edit edit_admin_place_path(place) %>
    <%= tb_grid_remove [:admin, place] %>
  </td>
</tr>

app/views/admin/places/edit.html.erb
<%= tb_breadcrumb link_to(Place.model_name.human.pluralize, admin_places_path), t('titles.edit', model_name: Place.model_name.human) %>

<%= render 'form' %>

app/views/admin/places/index.html.erb
<%= tb_breadcrumb Place.model_name.human.pluralize %>
<%= render partial: 'list' %>
<%= tb_button_new new_admin_place_path, t('links.new', model: Place.model_name.human) %>

app/views/admin/places/new.html.erb
<%= tb_breadcrumb link_to(Place.model_name.human.pluralize, admin_places_path), t('titles.new', model_name: Place.model_name.human) %>

<%= render 'form' %>

app/views/admin/places/show.html.erb
<%= tb_breadcrumb link_to(Place.model_name.human.pluralize, admin_places_path), t('titles.show', model_name: Place.model_name.human) %>

<% content_for :module, 'places' %>

<p> <%= image_tag @place.photo.url(:medium) %> </p>

<dl>
  <dt><%= Place.human_attribute_name 'enabled' %></dt>
  <dd><%= @place.enabled %></dd>
  <dt><%= Place.human_attribute_name 'code' %></dt>
  <dd><%= @place.code %></dd>
  <dt><%= Place.human_attribute_name 'name' %></dt>
  <dd><%= @place.name %></dd>
  <dt><%= Place.human_attribute_name 'abn' %></dt>
  <dd><%= @place.abn %></dd>
  <dt><%= Place.human_attribute_name 'printer_ip' %></dt>
  <dd><%= @place.printer_ip %></dd>
  <dt><%= Place.human_attribute_name 'printer_name' %></dt>
  <dd><%= @place.printer_name %></dd>
  <dt><%= Place.human_attribute_name 'address' %></dt>
  <dd><%= @place.address %></dd>
  <dt><%= Place.human_attribute_name 'phone' %></dt>
  <dd><%= @place.phone %></dd>
  <dt><%= Place.human_attribute_name 'description' %></dt>
  <dd><%= @place.description %></dd>
  <% if @place.map? %>
  <dt><%= Place.human_attribute_name 'map' %></dt>
  <dd>
    <iframe src="<%= @place.map %>"
            width="400"
            height="300"
            frameborder="0"
            style="border:0"></iframe>
  </dd>
  <% end %>
</dl>

<div class="form-group opening-hours" style="width: 400px;">
  <%= label :opening_hours, Place.human_attribute_name('opening_hours') %>
  <%= render partial:'/admin/opening_hours/list', locals:{place:@place} %>
</div>

<%= tb_button_edit edit_admin_place_path(@place) %>
<%= tb_button_back admin_places_path %>

app/views/admin/places/update_place.js.erb
$('#place_parent').html("<%= escape_javascript(options_for_select(@places)) %>");