config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  devise_for :users

  root 'home#index'

  get 'pick_up/when/:place_id/:date', to: 'pick_up#dates', as: :pick_up_dates

  resources :pick_up, except:[:new] do
    new do
      get ':place_id', to: :new, as: ''
    end
  end

  get 'cart/add/:product_id',                to: 'cart#modal',      as: :cart_new_item
  post 'cart/add',                           to: 'cart#create',     as: :cart_item_sizables
  post 'cart/add',                           to: 'cart#create',     as: :cart_item_quantitables
  post 'cart/add',                           to: 'cart#create',     as: :cart_item_sizable_additionables
  post 'cart/add',                           to: 'cart#create',     as: :cart_item_splittables
  post 'cart/add',                           to: 'cart#create',     as: :cart_item_additionables
  post 'cart/calculate',                     to: 'cart#calculate',  as: :cart_item_calculate
  delete 'cart/:id',                         to: 'cart#destroy',    as: :cart_remove_item

  get '/cart/:mode/:product_id/:side/ingredients', to: 'cart#ingredients',as: :cart_product_items

  controller :toppings do
    post 'index',       to: :index,         as: :toppings
    post 'add',         to: :add,           as: :add_topping
    post 'calculate',   to: :calculate,     as: :calulate_toppings
    post 'toppings',    to: :add_to_cart,   as: :add_toppings_to_cart
  end

  get 'cart/price',                               to: 'cart#price',    as: :cart_price
  get 'cart(/:product_id)',                       to: 'cart#index',    as: :cart
  post 'cart/mode',                               to: 'cart#mode',     as: :cart_mode
  get 'cart/:mode/:side/:category_id(/:size_id)', to: 'cart#carousel', as: :cart_carousel

  get 'checkout_modal', to: 'checkout#modal', as: :checkout_modal

  resources :orders, only: [:create, :destroy, :show]
  get 'checkout/:code',        to: 'orders#index',   as: :checkout
  get 'orders/:code/update',   to: 'orders#update',  as: :order_update
  get 'orders/:code/print',    to: 'orders#print',   as: :order_print
  get 'checkout/:code/success',to: 'orders#success', as: :order_success
  match 'checkout/confirm',    to: 'orders#confirm', as: :checkout_confirm, via: [:get, :post]

  controller :home do
    get 'shopping',          to: :shopping,     as: :shopping
    get 'contact',           to: :contact,      as: :contact
    post 'contact',          to: :send_message, as: :send_message
    get 'about',             to: :about,        as: :about
    get 'menu(/:active)',    to: :menu,         as: :menu
    get 'order/product/:id', to: :product,      as: :product
    get 'privacy',           to: :privacy,      as: :privacy
    get 'terms',             to: :terms,        as: :terms
    get 'returns',           to: :returns,      as: :returns
  end

  namespace :admin do

    root 'home#index'
    get 'home',    to: 'home#index',   as: :home
    get 'sign_in', to: 'home#sign_in', as: :sign_in

    resources :sizes
    resources :categories
    resources :product_types
    resources :users
    resources :customers
    resources :chefs
    resources :oven_time
    resources :orders, except: [:new, :create, :edit]
    
    get 'live/customer', to:'orders#live_customer', as: :order_live_customer
    get 'live(/:place_id)/:live_type', to:'orders#live', as: :order_live
    get 'order/:id/change_order_status', to:'orders#change_order_status', as: :order_change_order_status

    get 'products/options', to:'products#options', as: :products_reload_options
    resources :products

    get 'products/:product_id/prices/new', to:'prices#new', as: :price_new
    resources :prices

    resources :places do
      post 'opening_hours(/:opening_hour_id)/shifts/add', to: 'shifts#new', as: :new_opening_hour_shift_add
      patch 'opening_hours/:opening_hour_id/shifts/add', to: 'shifts#new', as: :opening_hour_shift_add
      resources :opening_hours do
        resources :shifts, only: [:destroy, :index]
      end
    end
  end
end

app/models/order.rb
require 'digest/sha1'

class Order < ActiveRecord::Base

  belongs_to :customer
  belongs_to :pick_up

  after_create :create_code

  before_destroy :before_destroy

  has_one :payment

  #0=pending  --> being prepared by the customer
  #1=sent     --> sent to securepay
  #2=approved --> approved by securepay
  #3=declined --> declined by securepay
  #3=canceled --> declined by securepay
  enum state: [:pending, :sent, :approved, :declined, :cancelled, :expired]

  #processing --> approved and wating to be printed
  #printed    --> already printed
  #oven       --> in oven
  #delivered  --> client picked up
  enum status: [:processing, :printed, :oven, :delivered]

  validates :state,
            presence: true

  validates :price,
            presence: true

  validates :customer,
            presence: true

  validates :pick_up,
            presence: true

  validates :ip_address,
            presence: true

  has_many :items, -> {order id: :desc},
           dependent: :destroy,
           class_name:'OrderItem'

  def self.create cart, ip_address
    order = Order.new customer:cart.customer,
                         state:Order.states[:pending],
                         price:cart.total,
                       pick_up:PickUp.new(place:cart.pick_up.place, date:cart.pick_up.date, created_at:cart.pick_up.created_at),
                    ip_address:ip_address

    cart.items.each do |cart_item|
      order.create_item cart_item
    end
    return order
  end

  def tax
    value = self.price/0.11
    Money.new(value, 'AUD').to_s
  end

  def create_item cart_item
    case cart_item
      when CartItemSplittable
        self.items << OrderItemSplittable.create(self, cart_item)
      when CartItemSizableAdditionable
        self.items << OrderItemSizableAdditionable.create(self, cart_item)
      when CartItemSizable
        self.items << OrderItemSizable.create(self, cart_item)
      when CartItemAdditionable
        self.items << OrderItemAdditionable.create(self, cart_item)
      when CartItemQuantitable
        self.items << OrderItemQuantitable.create(self, cart_item)
    end
  end

  def self.current customer
    find_by customer:customer
  end

  def self.current_pending customer
    find_by customer:customer, state:Order.states[:pending]
  end

  def allow_send?
    self.pending? || self.declined?
  end

  def post
    self.attempts+=1
    self.sent!
  end

  def decline!
    self.declined!
  end

  def max_of_attempts?
    self.attempts == 3
  end

  def approve!
    self.approved!
    self.processing!
    CustomerMailer.new_order(self).deliver
  end

  def check_expiration
    if self.pending? && self.pick_up.expired?
      self.expired!
      self.save
    end
  end

private

  def create_code
    self.code = "#{self.pick_up.place.code}#{self.id.to_s.rjust(8, '0')}"
    save
  end

  def before_destroy
    self.payment.destroy if self.payment.present?
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController

  before_action :set_order, only: [:show, :destroy, :print, :change_order_status]

  # GET /admin/orders
  # GET /admin/orders.json
  def index

    query = Order.all

    filter = false

    if params['code'].present?
      query = query.where code: params['code'].to_s
      filter = true
    end

    if params['place_id'].present?
      query = query.joins(pick_up: :place)
                   .where(places: {id:params[:place_id].to_i})
      filter = true
    end

    if params['customer_id'].present?
      query = query.joins(:customer)
                   .where(customers: {id:params[:customer_id].to_i})
      filter = true
    end

    if params['state'].present?
      query = query.where(state: params[:state])
      filter = true
    end

    if params['attempts'].present?
      query = query.where(attempts: params[:attempts])
      filter = true
    end

    if params['date_from'].present? && params['date_to'].present?

      from = params[:date_from].to_datetime.change({hour:00 , min:00 , sec:00 })
      to = params[:date_to].to_datetime.change({hour:23 , min:59 , sec:59 })

      query = query.where("created_at >= :start_date AND created_at <= :end_date",
              {start_date: from, end_date: to})
      filter = true
    end

    if params['pick_date_from'].present? && params['pick_date_to'].present?

      pick_from = params[:pick_date_from].to_datetime.change({hour:00 , min:00 , sec:00 })
      pick_to = params[:pick_date_to].to_datetime.change({hour:23 , min:59 , sec:59 })

      query = query.joins(:pick_up)
                   .where('pick_ups.date >= :start_date and pick_ups.date <= :end_date',
                    {start_date: pick_from, end_date: pick_to})
      filter = true
    end

    unless filter
      query = query.limit(50)
    end

    respond_to do |format|
      format.html { @orders = query.order(created_at: :desc) }
      format.json { @orders = query.order(created_at: :desc) }
    end
  end

  # GET /admin/orders.json
  def show
    respond_to do |format|
      format.html { @order }
      format.json { render json: @order, methods: :tax, except:[:state, :notes, :ip_address, :customer_id, :pick_up_id, :created_at, :created_by, :updated_at, :updated_by, :attempts],
                                    include: [{customer: {except:[:created_at, :created_by, :updated_at, :updated_by]}},
                                       {pick_up: {methods: :date_s, except:[:date, :created_at, :created_by, :updated_at, :updated_by],
                                          include:{place: {methods: :printer_ip_s, except: [:map, :photo_file_name, :photo_content_type, :photo_file_size, :photo_updated_at, :code, :enabled, :printer_ip, :created_at, :created_by, :updated_at, :updated_by, :description]}}}},
                                          items: {except: [:size_id, :notes, :order_id, :product_id, :quantity, :created_at, :created_by, :updated_at, :updated_by, :first_half_id, :second_half_id],
                                            include: [{first_half:{except: [:size_id, :notes, :order_id, :product_id, :quantity, :created_at, :created_by, :updated_at, :updated_by, :first_half_id, :second_half_id]}},
                                                      {second_half:{except: [:size_id, :notes, :order_id, :product_id, :quantity, :created_at, :created_by, :updated_at, :updated_by, :first_half_id, :second_half_id]}}]}]}
    end
  end

  # DELETE /admin/orders/id
  # DELETE /admin/orders/id.json
  def destroy
    begin
      @order.destroy
      respond_to do |format|
        format.html { redirect_to admin_orders_url, notice: t('messages.deleted', model:Order.model_name.human) }
        format.json { head :no_content }
      end
    rescue ActiveRecord::InvalidForeignKey => e
      flash[:error] = t 'errors.messages.delete_fail.being_used', model:@order.code
      flash[:error_details] = e
      redirect_to [:admin, @order]
    rescue ActiveRecord::StatementInvalid => e
      flash[:error] = t 'errors.messages.ops'
      flash[:error_details] = e
      redirect_to [:admin, @order]
    end
  end

  # GET /admin/live
  def live
    
    if params[:live_type].present? && params[:live_type] == "kitchen"
      query = Order.approved.where('status = ? or status = ?', Order.statuses[:processing], Order.statuses[:printed])
  
      if params[:place_id].present?
        query = query.joins(pick_up: :place)
                     .where(places: {id:params[:place_id].to_i})
      else
        query = query.joins :pick_up
      end
    else
      query = Order.approved.where('status = ?', Order.statuses[:oven])
  
      if params[:place_id].present?
        query = query.joins(pick_up: :place)
                     .where(places: {id:params[:place_id].to_i})
      else
        query = query.joins :pick_up
      end
    end

    @orders = query.order 'pick_ups.date ASC, id ASC'
    @place = params[:place_id].present? ? Place.find(params[:place_id]).name : "All"
    @live_type = params[:live_type]
  end

  # GET /admin/order/id/change_order_status
  def change_order_status
    
    unless @order.delivered?
      
      if (@order.processing? || @order.printed?)
        @order.oven!
      else
        @order.delivered!
      end
      
      @order.save!
    end
    render nothing:true, status: :ok
  end

  # GET /admin/live/customer
  def live_customer
    
    query = Order.approved.where('status <> ?', Order.statuses[:delivered])
  
    @orders = query.order 'status DESC, id ASC'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include PickUpConfiguratedConcern
  include CartConcern

  skip_before_filter :verify_authenticity_token, only: [:confirm]

  skip_before_action :check_pending_order

  before_action :authenticate_customer!, except: [:confirm]

  before_action :pick_up_configurated?, only: [:create]

  before_action :set_cart, only: [:create, :confirm]

  before_action :set_order, only: [:reload, :update, :index, :destroy, :confirm, :success, :fail, :print, :show]

  # POST /orders
  def create
    @order = @cart.create_order request.remote_ip
    if @order
      redirect_to checkout_path(@order.code)
    else
      redirect_to cart_path, notice:'Ops..'
    end
  end

  def show
    respond_to do |format|
      format.html { @order }
      format.json { render json: @order, methods: :tax, except:[:state, :notes, :ip_address, :customer_id, :pick_up_id, :created_at, :created_by, :updated_at, :updated_by, :attempts],
                                    include: [{customer: {except:[:created_at, :created_by, :updated_at, :updated_by]}},
                                       {pick_up: {methods: :date_s, except:[:date, :created_at, :created_by, :updated_at, :updated_by],
                                          include:{place: {methods: :printer_ip_s, except: [:map, :photo_file_name, :photo_content_type, :photo_file_size, :photo_updated_at, :code, :enabled, :printer_ip, :created_at, :created_by, :updated_at, :updated_by, :description]}}}},
                                          items: {except: [:size_id, :notes, :order_id, :product_id, :quantity, :created_at, :created_by, :updated_at, :updated_by, :first_half_id, :second_half_id],
                                            include: [{first_half:{except: [:size_id, :notes, :order_id, :product_id, :quantity, :created_at, :created_by, :updated_at, :updated_by, :first_half_id, :second_half_id]}},
                                                      {second_half:{except: [:size_id, :notes, :order_id, :product_id, :quantity, :created_at, :created_by, :updated_at, :updated_by, :first_half_id, :second_half_id]}}]}]}
    end
  end

  # GET /checkout/code
  def index
    if @order.approved?
      redirect_to order_success_path
    else
      @secure_pay = SecurePay.new @order
      @years = (Time.current.year.to_i..(Time.current + 10.years).year.to_i).to_a
      @months = Date::MONTHNAMES.compact
    end
  end

  # GET /orders/code/update
  def update
    if @order.allow_send?
      @order.post
      render nothing:true, status: :ok
    else
      render nothing:true, status: :unprocessable_entity
    end
  end

  def print
    @order.printed!
    render nothing:true, status: :ok
  end

  # DELETE /orders/1
  def destroy
    if @order.pending? || @order.sent?
      code = @order.code
      @order.cancelled!
      redirect_to cart_path, notice: t('messages.cancelled', model:"#{Order.model_name.human} #{code}")
    else
      redirect_to cart_path
    end
  end

  # GET|POST /checkout/confirm
  def confirm

    if @order.sent? && params[:summarycode].present?

      if params[:summarycode] == SecurePay::APPROVED
        @order.approve!
      else
        @order.decline!
      end

      settdate = nil
      if params[:settdate].present?
        settdate = params[:settdate].to_datetime
      end

      @order.payment.destroy if @order.payment.present?

      @order.create_payment status: params[:summarycode],
                              code: params[:rescode],
                       description: params[:restext],
               bank_transaction_id: params[:txnid],
                     bank_settdate: settdate,
                       card_number: params[:pan],
                   card_expirydate: params[:expirydate],
                         timestamp: params[:timestamp].to_datetime,
                       fingerprint: params[:fingerprint],
                        ip_address: request.remote_ip,
                      full_request: params.to_s

      render nothing:true, status: :ok
    else
      render nothing:true, status: :forbidden
    end
  end

private

    # Use callbacks to share common setup or constraints between actions.
    def set_order
      if params[:refid].present?
        @order = Order.find_by code:params[:refid]
      elsif params[:code].present?
        @order = Order.find_by code:params[:code], customer:current_customer
      else
        @order = current_customer.orders.last
      end
      @order.check_expiration if @order.present?
      redirect_to cart_path if @order.nil?
    end
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/admin/orders/_list.html.erb
<table class="table table-condensed table-bordered">
  <thead>
    <tr>
      <th style="width:30px;"> # </th>
      <th><%= Order.human_attribute_name :code %></th>
      <th><%= Customer.model_name.human %></th>
      <th><%= PickUp.model_name.human %> <%= Place.model_name.human %></th>
      <th><%= PickUp.model_name.human %> <%= PickUp.human_attribute_name :date %></th>
      <th><%= Order.human_attribute_name :price %></th>
      <th><%= Order.human_attribute_name :state %></th>
      <th><%= Order.human_attribute_name :status %></th>
      <th><%= Order.human_attribute_name :ip_address %></th>
      <th style="width: 50px;"><%= Order.human_attribute_name :attempts %></th>
      <th style="width: 140px;"><%= Order.human_attribute_name :created_at %></th>
      <th style="width: 75px;"></th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <td colspan="4"></td>
      <td style="text-align: right;">Sum (<%= @orders.size %>)</td>
      <td><%= number_to_currency @orders.sum(:price) %></td>
      <td colspan="5"></td>
    </tr>
  </tfoot>
  <tbody>
    <%= render @orders %>
  </tbody>

</table>

app/views/admin/orders/_order.html.erb
<tr>
  <td> <%= order.id %> </td>
  <td> <%= order.code %> </td>
  <td> <%= order.customer.name %> </td>
  <td> <%= order.pick_up.place.name %> </td>
  <td> <%= order.pick_up.date.to_formatted_s :long %> </td>
  <td> <%= number_to_currency order.price %> </td>
  <td>
    <% if order.pending? %>
      <i class="glyphicon glyphicon-info-sign"></i>
    <% elsif order.sent? %>
      <i class="glyphicon glyphicon-question-sign"></i>
    <% elsif order.approved? %>
      <i class="glyphicon glyphicon-ok-circle"></i>
    <% elsif order.declined? %>
      <i class="glyphicon glyphicon-exclamation-sign"></i>
    <% elsif order.cancelled? %>
      <i class="glyphicon glyphicon-ban-circle"></i>
    <% elsif order.expired? %>
      <i class="glyphicon glyphicon-minus-sign"></i>
    <% end %>
    <%= order.state %>
  </td>
  <td> <%= order.status || '--' %> </td>
  <td> <%= order.ip_address %> </td>
  <td> <%= order.attempts %> </td>
  <td> <%= order.created_at.to_formatted_s :long %> </td>
  <td>
    <%= tb_grid_show [:admin, order] %>
    <%= tb_grid_remove [:admin, order] %>
    <% if order.payment.present? %>
      <a href="JavaScript:void(0);" class="expanable" data-target="#order_payment_<%= order.payment.id %>">
        <i class="glyphicon glyphicon-plus"></i>
      </a>
    <% end %>
    <% if order.approved? %>
      <a href="JavaScript:void(0);" class="print" data-url="<%= admin_order_path(order.id, :json) %>">
        <i class="glyphicon glyphicon-print"></i>
      </a>
    <% end %>
  </td>
</tr>
<% if order.payment.present? %>
<tr id="order_payment_<%= order.payment.id %>" style="display:none;">
  <td colspan="11">
    <%= render 'admin/payments/list', payments:[order.payment] %>
  </td>
</tr>
<% end %>

app/views/admin/orders/index.html.erb
<% content_for :module, 'orders' %>
<%= tb_breadcrumb Order.model_name.human.pluralize %>
<%= form_tag admin_orders_path, method:'get', role:'form' do %>

  <div class="row">

    <div class="col-md-2 col-sm-2">
      <div class="form-group">
        <%= label :code, Order.human_attribute_name('code') %>
        <%= text_field_tag :code, params['code'], class:'form-control', placeholder:'Code' %>
      </div>
    </div>

    <div class="col-md-2 col-sm-2">
      <div class="form-group">
        <%= label :place_id, Place.model_name.human %>
        <%= select_tag 'place_id',
                        options_from_collection_for_select(Place.order('name'), 'id', 'name', params['place_id']),
                        {include_blank: t('helpers.select.all'), class:'form-control'} %>
      </div>
    </div>

    <div class="col-md-4 col-sm-4">
      <div class="form-group">
        <%= label :customer_id, Customer.model_name.human %>
        <%= select_tag 'customer_id',
                        options_from_collection_for_select(Customer.order('name'), 'id', 'full_name', params['customer_id']),
                        {include_blank: t('helpers.select.all'), class:'form-control'} %>
      </div>
    </div>

    <div class="col-md-2 col-sm-2">
      <div class="form-group">
        <%= label :state, Order.human_attribute_name('state') %>
        <%= select_tag 'state',
                        options_for_select(Order.states, params['state']),
                        {include_blank: t('helpers.select.all'), class:'form-control'} %>
      </div>
    </div>

    <div class="col-md-2 col-sm-2">
      <div class="form-group">
        <%= label :attempts, Order.human_attribute_name('attempts') %>
        <%= select_tag 'attempts',
                        options_for_select([0,1,2,3], params['attempts']),
                        {include_blank: t('helpers.select.all'), class:'form-control'} %>
      </div>
    </div>

    <div class="col-md-3 col-sm-3">
      <div class="form-group">
        <%= label :pick_date_from, "#{PickUp.model_name.human} #{Order.human_attribute_name('date')} From" %>
        <%= date_field_tag(:pick_date_from, params['pick_date_from'], class:'form-control') %>
      </div>
    </div>

    <div class="col-md-3 col-sm-3">
      <div class="form-group">
        <%= label :pick_date_to, "#{PickUp.model_name.human} #{Order.human_attribute_name('date')} To" %>
        <%= date_field_tag(:pick_date_to, params['pick_date_to'], class:'form-control') %>
      </div>
    </div>

    <div class="col-md-3 col-sm-3">
      <div class="form-group">
        <%= label :date_from, "#{Order.human_attribute_name('created_at')} From" %>
        <%= date_field_tag(:date_from, params['date_from'], class:'form-control') %>
      </div>
    </div>

    <div class="col-md-3 col-sm-3">
      <div class="form-group">
        <%= label :date_to, "#{Order.human_attribute_name('created_at')} To" %>
        <%= date_field_tag(:date_to, params['date_to'], class:'form-control') %>
      </div>
    </div>

  </div>

  <%= tb_submit_search %>

<% end %>
<br /><br />
<%= render 'list' %>

<%= render 'print' %>

app/views/admin/orders/live.html.erb
<% content_for :module, 'orders' %>
<% content_for :default_class, 'container-fluid' %>

<% if @place.present? %>
	<% @place_name = @place + " -" %>
<% end %>

<div class="row live-title">
	<% if @live_type == "kitchen" %>
		<h1><%= @place_name %> Kithen Orders</h1>
	<% else %>
		<h1><%= @place_name %> Wrap-up Orders</h1>
	<% end %>
</div>

<div class="row">

	<% @orders.each_with_index do |order, index| %>
	
		<% @ready_time = order.updated_at.advance(:minutes => + order.pick_up.place.oven_time.time) %>
		<% @order = order %>
		
		<div class="col-md-4 col-sm-4 order">
			<a class="order-item-anchor" onclick="JavaScript:showLivePopup(this);">
				<div class="order-inner">
					
					<% if order.oven? %>
						<div class="wrap-up-order-status <%= order.oven? && @ready_time <= Time.now ? "ready" : "oven" %>">
							<% if order.oven? && @ready_time <= Time.now  %>
								Ready to Deliver
							<% elsif %>
								<%= TimeDifference.between(Time.now, @ready_time).in_minutes.to_i %> minutes to be Ready
							<% end %>
						</div>
					<% end %>
					
					<h4>
						<span class="order-id"><%= @order.id %></span>
						<span class="order-not-printed">
							<% if @order.processing? %>
								<i class="glyphicon glyphicon-ban-circle"></i>
							<% end %>
							<i class="glyphicon glyphicon-print"></i>
						</span>
						<i class="glyphicon glyphicon-time"></i>
						<%= @order.pick_up.date.to_formatted_s :short %>
						<span class="order-customer"><%= @order.customer.name %></span>
					</h4>
					
					<div class="order-item">
						<%= render 'orders/resume' %>
					</div>
			    </div>
			    <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="myMedianModalLabel">
				  <div class="modal-dialog modal-md">
				    <div class="modal-content">
				    	<div class="modal-header">
						    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							<h4 class="modal-title" id="exampleModalLabel">Order actions</h4>
						</div>
						<div class="row">
							<div class="col-xs-12 print">
								<a href="JavaScript:void(0);" class="btn btn-primary print-button" data-url="<%= admin_order_path(@order.id, :json) %>">
									<i class='fa fa-spinner fa-spin' style='display:none;'></i>
									<i class="glyphicon glyphicon-exclamation-sign" style='display:none;'></i>
									<i class="glyphicon glyphicon-print"></i>
									<%= @order.code %>
								</a>
							</div>
							<div class="col-xs-6 danger">
								<a class="btn btn-danger" onclick="JavaScript:hideLivePopup(this);">
									<i class="glyphicon glyphicon-remove"></i>
									Cancel
								</a>
							</div>
							<div class="col-xs-6 success">
								<%= link_to admin_order_change_order_status_path(@order), class:'btn btn-success oven', remote:true do %>
									<i class="glyphicon glyphicon-ok"></i>
									<i class="fa fa-spinner fa-spin" style="display:none;"></i>
									<% if @order.processing? || @order.printed? %>
										Oven
									<% else %>
										Deliver
									<% end %>
								<% end %>
							</div>
						</div>      	
				    </div>
				  </div>
				</div>
			</a>
		</div>
	<% end %>
</div>

<%= javascript_tag "reloadPage(60000);" %>

app/views/admin/orders/show.html.erb
<%= tb_breadcrumb link_to(Order.model_name.human.pluralize, admin_orders_path), t('titles.show', model_name: Order.model_name.human) %>

<dl>
  <dt><%= Order.human_attribute_name :code %></dt>
  <dd><%= @order.code %></dd>
  <dt><%= Order.human_attribute_name :price %></dt>
  <dd><%= number_to_currency @order.price %></dd>
  <dt><%= Order.human_attribute_name :state %></dt>
  <dd>
    <% if @order.pending? %>
      <i class="glyphicon glyphicon-info-sign"></i>
    <% elsif @order.sent? %>
      <i class="glyphicon glyphicon-question-sign"></i>
    <% elsif @order.approved? %>
      <i class="glyphicon glyphicon-ok-circle"></i>
    <% elsif @order.declined? %>
      <i class="glyphicon glyphicon-exclamation-sign"></i>
    <% end %>
    <%= @order.state %>
  </dd>
  <dt><%= PickUp.model_name.human %> <%= Place.model_name.human %></dt>
  <dd><%= @order.pick_up.place.name %></dd>
  <dt><%= PickUp.model_name.human %> <%= PickUp.human_attribute_name :date %></dt>
  <dd><%= @order.pick_up.date.to_formatted_s :long %></dd>
  <dt><%= Order.human_attribute_name :ip_address %></dt>
  <dd><%= @order.ip_address %></dd>
  <dt><%= Order.human_attribute_name :created_at %></dt>
  <dd><%= @order.created_at.to_formatted_s :long %></dd>
</dl>

<h3>Items</h3>
<%= render 'admin/order_items/list', order_items:@order.items %>

<h3>Payment</h3>
<%= render 'admin/payments/list', payments:[@order.payment] if @order.payment.present? %>

<%= tb_button_back admin_orders_path %>