config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  devise_for :users

  root 'home#index'

  get 'pick_up/when/:place_id/:date', to: 'pick_up#dates', as: :pick_up_dates

  resources :pick_up, except:[:new] do
    new do
      get ':place_id', to: :new, as: ''
    end
  end

  get 'cart/add/:product_id',                to: 'cart#modal',      as: :cart_new_item
  post 'cart/add',                           to: 'cart#create',     as: :cart_item_sizables
  post 'cart/add',                           to: 'cart#create',     as: :cart_item_quantitables
  post 'cart/add',                           to: 'cart#create',     as: :cart_item_sizable_additionables
  post 'cart/add',                           to: 'cart#create',     as: :cart_item_splittables
  post 'cart/add',                           to: 'cart#create',     as: :cart_item_additionables
  post 'cart/calculate',                     to: 'cart#calculate',  as: :cart_item_calculate
  delete 'cart/:id',                         to: 'cart#destroy',    as: :cart_remove_item

  get '/cart/:mode/:product_id/:side/ingredients', to: 'cart#ingredients',as: :cart_product_items

  controller :toppings do
    post 'index',       to: :index,         as: :toppings
    post 'add',         to: :add,           as: :add_topping
    post 'calculate',   to: :calculate,     as: :calulate_toppings
    post 'toppings',    to: :add_to_cart,   as: :add_toppings_to_cart
  end

  get 'cart/price',                               to: 'cart#price',    as: :cart_price
  get 'cart(/:product_id)',                       to: 'cart#index',    as: :cart
  post 'cart/mode',                               to: 'cart#mode',     as: :cart_mode
  get 'cart/:mode/:side/:category_id(/:size_id)', to: 'cart#carousel', as: :cart_carousel

  get 'checkout_modal', to: 'checkout#modal', as: :checkout_modal

  resources :orders, only: [:create, :destroy, :show]
  get 'checkout/:code',        to: 'orders#index',   as: :checkout
  get 'orders/:code/update',   to: 'orders#update',  as: :order_update
  get 'orders/:code/print',    to: 'orders#print',   as: :order_print
  get 'checkout/:code/success',to: 'orders#success', as: :order_success
  match 'checkout/confirm',    to: 'orders#confirm', as: :checkout_confirm, via: [:get, :post]

  controller :home do
    get 'shopping',          to: :shopping,     as: :shopping
    get 'contact',           to: :contact,      as: :contact
    post 'contact',          to: :send_message, as: :send_message
    get 'about',             to: :about,        as: :about
    get 'menu(/:active)',    to: :menu,         as: :menu
    get 'order/product/:id', to: :product,      as: :product
    get 'privacy',           to: :privacy,      as: :privacy
    get 'terms',             to: :terms,        as: :terms
    get 'returns',           to: :returns,      as: :returns
  end

  namespace :admin do

    root 'home#index'
    get 'home',    to: 'home#index',   as: :home
    get 'sign_in', to: 'home#sign_in', as: :sign_in

    resources :sizes
    resources :categories
    resources :product_types
    resources :users
    resources :customers
    resources :chefs
    resources :oven_time
    resources :orders, except: [:new, :create, :edit]
    
    get 'live/customer', to:'orders#live_customer', as: :order_live_customer
    get 'live(/:place_id)/:live_type', to:'orders#live', as: :order_live
    get 'order/:id/change_order_status', to:'orders#change_order_status', as: :order_change_order_status

    get 'products/options', to:'products#options', as: :products_reload_options
    resources :products

    get 'products/:product_id/prices/new', to:'prices#new', as: :price_new
    resources :prices

    resources :places do
      post 'opening_hours(/:opening_hour_id)/shifts/add', to: 'shifts#new', as: :new_opening_hour_shift_add
      patch 'opening_hours/:opening_hour_id/shifts/add', to: 'shifts#new', as: :opening_hour_shift_add
      resources :opening_hours do
        resources :shifts, only: [:destroy, :index]
      end
    end
  end
end

app/views/admin/navigation/_live.html.erb
<li class="dropdown <%= is_live ? 'active' : '' %>">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      Live
    </a>
    <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
    	<li class="dropdown-submenu">
			<a tabindex="-1" href="#">Kitchen</a>
            <ul class="dropdown-menu">
        		<li> <%= link_to 'All', admin_order_live_path(nil, "kitchen"), :onclick => 'addAjaxLoader();' %> </li>
              	<% Place.where(enabled:true).each do |place| %>
                	<li> <%= link_to place.name, admin_order_live_path(place, "kitchen"), :onclick => 'addAjaxLoader();' %> </li>
              	<% end %>
            </ul>
		</li>
		<li class="divider"></li>
    	<li class="dropdown-submenu">
			<a tabindex="-1" href="#">Wrap-up</a>
            <ul class="dropdown-menu">
        		<li> <%= link_to 'All', admin_order_live_path(nil, "wrapup"), :onclick => 'addAjaxLoader();' %> </li>
              	<% Place.where(enabled:true).each do |place| %>
                	<li> <%= link_to place.name, admin_order_live_path(place, "wrapup"), :onclick => 'addAjaxLoader();' %> </li>
              	<% end %>
            </ul>
		</li>
		<li class="divider"></li>
		<li>
			<%= link_to 'Customer view', admin_order_live_customer_path, :onclick => 'addAjaxLoader();' %>
		</li>            
    </ul>
</li>

app/views/admin/navigation/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to t('brand'), root_path, class: 'navbar-brand', :onclick => 'addAjaxLoader();' %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <% if user_signed_in? %>
      <ul class="nav navbar-nav menu" role="menu" aria-labelledby="dropdownMenu">
        <% if current_user.admin? %>
          <li <%= is_active 'admin/product_types' %>>
            <%= link_to ProductType.model_name.human.pluralize, admin_product_types_path, :onclick => 'addAjaxLoader();' %>
          </li>
          <li <%= is_active 'admin/categories' %>>
            <%= link_to Category.model_name.human.pluralize, admin_categories_path, :onclick => 'addAjaxLoader();' %>
          </li>
          <li <%= is_active 'admin/sizes' %>>
            <%= link_to Size.model_name.human.pluralize, admin_sizes_path, :onclick => 'addAjaxLoader();' %>
          </li>
          <li <%= is_active 'admin/products' %>>
            <%= link_to Product.model_name.human.pluralize, admin_products_path, :onclick => 'addAjaxLoader();' %>
          </li>
          <li <%= is_active 'admin/places' %>>
            <%= link_to Place.model_name.human.pluralize, admin_places_path, :onclick => 'addAjaxLoader();' %>
          </li>
          <li <%= is_active 'admin/users' %>>
            <%= link_to User.model_name.human.pluralize, admin_users_path, :onclick => 'addAjaxLoader();' %>
          </li>
          <li <%= is_active 'admin/customers' %>>
            <%= link_to Customer.model_name.human.pluralize, admin_customers_path, :onclick => 'addAjaxLoader();' %>
          </li>
          <li <%= !is_live ? is_active('admin/orders') : '' %>>
            <%= link_to Order.model_name.human.pluralize, admin_orders_path, :onclick => 'addAjaxLoader();' %>
          </li>
          <li <%= is_active 'admin/chefs' %>>
            <%= link_to Chef.model_name.human.pluralize, admin_chefs_path, :onclick => 'addAjaxLoader();' %>
          </li>
        <% end %>
        <%= render partial: 'admin/navigation/live' %>
		<%= render partial: 'admin/navigation/oven_time' %>
      </ul>
    <% end %>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.username %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li> <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, :onclick => 'addAjaxLoader();' %> </li>
            </ul>
          </li>
      <% end %>
    </ul>

  </div><!-- /.navbar-collapse -->
</nav>

app/views/admin/navigation/_oven_time.html.erb
<li>			
	<input id="ovenId" type="hidden" />
	<input id="ovenTime" type="hidden" />
	<input id="ovenTimePlaceId" type="hidden" />
	
  	<div class="row oven-time">
		<div class="col-xs-12">
          	<div class="input-group">
	            <button id="editOvenTimeBtn" type="button" class="btn btn-danger">
	            	Edit oven time
          			<i class="glyphicon glyphicon-chevron-right"></i>
          		</button>
            </div>
    	</div>
    </div>
    
	<div class="row oven-time-place" style="display: none;">
		<div class="col-xs-12">
          	<div>
          		<% Place.where(enabled:true).each do |place| %>
		          	<button type="button" class="btn btn-primary oven-time-place-btn" 
		          		data-oven-time-id="<%= place.oven_time.id %>"
		          		data-oven-time="<%= place.oven_time.time %>"
		          		data-place-id="<%= place.id %>" >
		          		
			      		<%= place.name %>
	            	</button>		            
	            <% end %>
            </div>
    	</div>
	</div>		    			
    
	<div class="row edit-oven-time" style="display: none;">	    		
    	<div class="col-xs-12">
          	<div class="input-group">
          		
	            <input id="newOvenTime" name="ovenTime" type="number" class="form-control" min="1" max="50" placeholder="Time!" maxlength="2" oninput="maxLengthCheck(this)" />
	            
	            <button id="cancelOvenTimeBtn" type="button" class="btn btn-danger">
	            	<i class="glyphicon glyphicon-remove-circle"></i>
	            	Cancel
	            </button>
		        <button id="saveOvenTimeBtn" type="button" class="btn btn-success spinnable">
		        	<i class="glyphicon glyphicon-ok-circle"></i>
      				<i class="fa fa-spinner fa-spin" style="display:none;"></i>
      				Save
      			</button>
            </div>
		</div>
	</div>	
</li>