config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  devise_for :users

  root 'home#index'

  get 'pick_up/when/:place_id/:date', to: 'pick_up#dates', as: :pick_up_dates

  resources :pick_up, except:[:new] do
    new do
      get ':place_id', to: :new, as: ''
    end
  end

  get 'cart/add/:product_id',                to: 'cart#modal',      as: :cart_new_item
  post 'cart/add',                           to: 'cart#create',     as: :cart_item_sizables
  post 'cart/add',                           to: 'cart#create',     as: :cart_item_quantitables
  post 'cart/add',                           to: 'cart#create',     as: :cart_item_sizable_additionables
  post 'cart/add',                           to: 'cart#create',     as: :cart_item_splittables
  post 'cart/add',                           to: 'cart#create',     as: :cart_item_additionables
  post 'cart/calculate',                     to: 'cart#calculate',  as: :cart_item_calculate
  delete 'cart/:id',                         to: 'cart#destroy',    as: :cart_remove_item

  get '/cart/:mode/:product_id/:side/ingredients', to: 'cart#ingredients',as: :cart_product_items

  controller :toppings do
    post 'index',       to: :index,         as: :toppings
    post 'add',         to: :add,           as: :add_topping
    post 'calculate',   to: :calculate,     as: :calulate_toppings
    post 'toppings',    to: :add_to_cart,   as: :add_toppings_to_cart
  end

  get 'cart/price',                               to: 'cart#price',    as: :cart_price
  get 'cart(/:product_id)',                       to: 'cart#index',    as: :cart
  post 'cart/mode',                               to: 'cart#mode',     as: :cart_mode
  get 'cart/:mode/:side/:category_id(/:size_id)', to: 'cart#carousel', as: :cart_carousel

  get 'checkout_modal', to: 'checkout#modal', as: :checkout_modal

  resources :orders, only: [:create, :destroy, :show]
  get 'checkout/:code',        to: 'orders#index',   as: :checkout
  get 'orders/:code/update',   to: 'orders#update',  as: :order_update
  get 'orders/:code/print',    to: 'orders#print',   as: :order_print
  get 'checkout/:code/success',to: 'orders#success', as: :order_success
  match 'checkout/confirm',    to: 'orders#confirm', as: :checkout_confirm, via: [:get, :post]

  controller :home do
    get 'shopping',          to: :shopping,     as: :shopping
    get 'contact',           to: :contact,      as: :contact
    post 'contact',          to: :send_message, as: :send_message
    get 'about',             to: :about,        as: :about
    get 'menu(/:active)',    to: :menu,         as: :menu
    get 'order/product/:id', to: :product,      as: :product
    get 'privacy',           to: :privacy,      as: :privacy
    get 'terms',             to: :terms,        as: :terms
    get 'returns',           to: :returns,      as: :returns
  end

  namespace :admin do

    root 'home#index'
    get 'home',    to: 'home#index',   as: :home
    get 'sign_in', to: 'home#sign_in', as: :sign_in

    resources :sizes
    resources :categories
    resources :product_types
    resources :users
    resources :customers
    resources :chefs
    resources :oven_time
    resources :orders, except: [:new, :create, :edit]
    
    get 'live/customer', to:'orders#live_customer', as: :order_live_customer
    get 'live(/:place_id)/:live_type', to:'orders#live', as: :order_live
    get 'order/:id/change_order_status', to:'orders#change_order_status', as: :order_change_order_status

    get 'products/options', to:'products#options', as: :products_reload_options
    resources :products

    get 'products/:product_id/prices/new', to:'prices#new', as: :price_new
    resources :prices

    resources :places do
      post 'opening_hours(/:opening_hour_id)/shifts/add', to: 'shifts#new', as: :new_opening_hour_shift_add
      patch 'opening_hours/:opening_hour_id/shifts/add', to: 'shifts#new', as: :opening_hour_shift_add
      resources :opening_hours do
        resources :shifts, only: [:destroy, :index]
      end
    end
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::BaseController

  skip_before_action :require_admin!, only: :sign_in

  def index
  end

  def sign_in
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include PickUpConfiguratedConcern

  before_action :set_product, only: [:product]
  before_action :set_category, only: [:category]

  # GET /
  def index
    render layout:'generic'
  end

  # GET /contact
  def contact
    @contact = Contact.new
  end

  def send_message
    @contact = Contact.new contact_params
    if verify_recaptcha(model: @contact, message:"Oh! It's error with reCAPTCHA!") and @contact.valid?
      ContactMailer.request_info(@contact.name, @contact.email, @contact.message).deliver
      flash[:success] = 'Message sent!'
      @contact = Contact.new
    end
    render 'contact'
  end

  # GET /about
  def about
    @chefs = Chef.order(:name)
  end

  # GET /menu
  def menu
    @categories = Category.with_shoppable_products
  end

  # GET /privacy
  def privacy
    render partial:'home/term', locals:{term:'privacy'}, layout: nil
  end

  # GET /terms
  def terms
    render partial:'home/term', locals:{term:'terms'}, layout: nil
  end

  # GET /returns
  def returns
    render partial:'home/term', locals:{term:'returns'}, layout: nil
  end

  private

      # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def set_category
      @category = Category.find(params[:id])
    end

    def set_cart
      @cart = Cart.current current_customer
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit :name,
                                      :email,
                                      :message
    end
end

app/helpers/home_helper.rb
module HomeHelper

  def slider_path image
    "https://caesars-prod.s3.amazonaws.com/assets/slider/#{image}"
  end

end

app/views/home/_category.html.erb
<div class="row">
  <% category.products.shoppable.each do |product| %>
    <div class="col-md-3 col-sm-6">
      <div class="shopping-item"> <!-- Shopping items -->
      	<h4 class="pull-left"> <%= product.name %> </h4><!-- Shopping item name / Heading -->
        <!-- Image -->
        <%= link_to product_path(product), {title: product.describe} do %>
          <%= image_tag product.photo.url(:large), class: 'img-responsive', alt: product.describe %>
        <% end %>
        
        <div class="clearfix"></div>
        <!-- Paragraph -->
        <% if product.type.sizable? %>
          <% product.prices.each do |price| %>
            <%= render partial:'shopping_price', locals:{name:price.size.name, value:price.value} %>
          <% end %>
        <% else %>
          <%= render partial:'shopping_price', locals:{name:'Price', value:product.price} %>
        <% end %>
        <!-- Buy now button -->
        <div class="visible-xs">
          <br>
          <%= add_to_cart_button product %>
        </div>
        <!-- Shopping item hover block & link -->
        <div class="item-hover br-red hidden-xs"></div>
          <% if customer_signed_in? %>
            <% if current_customer.cart.present? %>
              <% if !current_customer.cart.pick_up_configurated? %>
                <%= link_to t('links.add_to', model_name:Cart.model_name.human),
                    pick_up_index_path, class:'link hidden-xs' %>
              <% elsif product.type.additionable? %>
                <%= link_to t('links.add_to', model_name:Cart.model_name.human),
                    cart_path(product), class:'link hidden-xs' %>
              <% else %>
                <%= link_to t('links.add_to', model_name:Cart.model_name.human),
                    cart_new_item_path(product), remote:true, class:'link hidden-xs add_to_cart' %>
              <% end %>
            <% end %>
          <% else %>
            <%= link_to t('links.add_to', model_name:Cart.model_name.human),
                new_customer_registration_path, class:'link hidden-xs' %>
          <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/home/_privacy.html.erb
<h4>INTRODUCTION</h4>

<p>
  1.1 When you purchase a product from our store, as part of the buying and selling process, we collect the personal information you give us such as your name, surname, mobile and email address.
</p>

<p>
  1.2 When you browse our store, we also automatically receive your computer’s internet protocol (IP) address in order to provide us with information that helps us learn about your browser and operating system.
</p>

<p>
  1.3 Email marketing: With your permission by asking us for updates, we may send you emails about our store, new products and other updates.
</p>

<h4>CONSENT</h4>

<p>
  2.1 Little Cs is committed to ensure the privacy and security of all information collected from our users. In accordance with the privacy legislation applicable in Australia, this Privacy Policy outlines the information collection practices utilised by Little Cs, how that information is used and the choices you can make about the way the information you provide to us is collected and used. By using www.Littlecaesarspizzeria.com.au website, you agree to and consent to the collection, use and disclosure of personal information by Little Cs as set out in this policy.
</p>
<p>
  2.2 When you provide us with personal information to complete a transaction, verify your credit card, place an order, arrange for a delivery/pick-up a purchase, we imply that you consent to our collecting it and using it for that specific reason only.
</p>
<p>
  2.3 If we ask for your personal information for a secondary reason, like marketing, we will either ask you directly for your expressed consent, or provide you with an opportunity to say no.
</p>
<p>
  2.4 If after you opt-in, you change your mind, you may withdraw your consent for us to contact you, for the continued collection, use or disclosure of your information, at anytime, by contacting us at info@littlecs.com or mailing us at: Little Cs 1/1 Townsend Street Malaga Perth WA Australia 6090
</p>

<h4>USE AND DISCLOSE OF YOUR PERSONAL INFORMATION</h4>

<p>
  3.1 Little Cs uses your personal information for the purposes of: Providing our services to you, internal management needs, marketing needs if applicable, responding to enquires submitted to us, law requisition.
</p>
<p>
  3.2 When buying from us, your personal information is required to complete an online form as name, surname, mobile, email address and bank details. The information that you enter into the online form will be collected and saved by us. The information you supply to us is used to assess your requirements and to enable the relevant restaurant or takeaway delivery service to contact you in response to your enquiry.
</p>
<p>
  3.3 We may disclose your information to various third parties that provide services to us, including third parties that provide our payment gateway, marketing, logistics and technology support services.
</p>
<p>
  3.4 It is a condition of your use of the Little Cs website that you agree to allow your data to be disclosed to these third parties and for them to establish contact with you. If at any point in time you would like your saved data to be deleted from our system, please contact us and we will arrange to have your records deleted from our database.
</p>
<h4> SECURITY OF YOUR PERSONAL INFORMATION AND COOKIES </h4>
<p>
  4.1 All user details gathered by Little Cs are stored securely at all times and will never be provided to any unauthorised third parties. While being transmitted over the Internet, all credit card details are protected using SSL (Secure Socket Layer) 128-bit encryption. Little Cs has been verified for security and compliance to SSL standards by RapidSSL CA.
</p>
<p>
  4.2 Credit card details are handled by a 3rd party Payment Gateway called SecurePay. Little Cs will never save your actual credit card details. We will simply save a reference to your card, which is called a token. This token is provided to us by our Payment Gateway. Saving the token means that for future credit card transactions we can give you the option to charge the same card you used previously without having to re-enter the card details. You will still need to enter your Little Cs password to use this credit card. If, at any time, you wish the token to be removed please email us at info@littlecs.com and we will have these removed. In that case you would need to re-enter your card details on the next order. For the avoidance of doubt, Little Cs will not in any circumstances be liable to you, or third parties, for loss or damage arising from credit card fraud or identity theft.
</p>
<p>
  4.3 "Cookies" are pieces of information that our web page transfers to your computer's hard disk for record-keeping purposes. Cookies can make the Web more useful by storing information about your preferences on a particular site. The use of cookies is an industry standard and many Web sites use them to provide useful features for you. Cookies in and of themselves do not personally identify you, only your computer.
</p>
<p>
  4.4 We may, from time to time, use "cookies" to store your preferences, record session information and collect information on how you visit and access our webpages. We collect information on the Web pages visited by our customers in order to help us to continue improving our services.
</p>
<h4>CHANGE OF PERSONAL INFORMATION</h4>
<p>
  5.1 You may request access to your personal information in our customer account database, or seek correction of it, by contacting us via our Contact Us page.
</p>
<p>
  5.2 If you believe that Little Cs holds personal information about you in our customer account database that is not accurate, complete, up-to-date, relevant or information that is misleading then you may request its amendment and Little Cs will respond to your request within a reasonable time. Little Cs will not charge you for correcting your personal information.
</p>
<p>
  5.3 If Little Cs no longer needs your personal information for any the purposes set out in this policy, or as otherwise required by law, Little Cs will take such steps as are reasonable in the circumstances to destroy the information or to de-identify it.
</p>
<p>
  5.4 Little Cs will take reasonable steps to protect the personal information it holds from misuse, interference and loss and from unauthorised access, modification or disclosure.
</p>

<h4>CHANGES TO THIS PRIVACY POLICY</h4>

<p>
  6.1 This policy may be revised from time to time, as new features are added to the site or the legislation changes. Please check back periodically for updates and additions. If you have any concerns or queries about the Privacy Policy of Little Cs or would like more information, please contact us using the details displayed in the footer of our website.
</p>

<h4>COMPLAINTS PROCEDURE</h4>

<p>
  7.1 If you would like to: access, correct, amend or delete any personal information we have about you, register a complaint, or simply want more information contact our Privacy Compliance Officer at info@littlecs.com or by mail at Little Cs
</p>
<p>
  [Re: Privacy Compliance Officer]
</p>
<p>
  [1/1 Townsend Street Malaga Perth WA Australia 6090]
</p>

app/views/home/_returns.html.erb
<p>
  1.1 Our policy lasts 24 hours. If 24 hours have gone by since your purchase, unfortunately we can’t offer you a refund or exchange.
</p>

<p>
  1.2 We only do an exchange or refund if we have made a mistake to your order. No refunds or exchange will be given if you cannot prove that the mistake was made by us.
</p>

<p>
  1.3 To be eligible for a refund or exchange, you must have all the requirements below:
  <ul>
    <li>Item must be in the same condition that you received it</li>
    <li>Item must be in the original packaging</li>
    <li>Show the purchase receipt</li>
  </ul>
</p>

<p>
  1.4 Additional non-returnable items:
  <ul>
    <li>Gift cards</li>
    <li>Beverages</li>
  </ul>
</p>

<p>
  To complete your return, we require a receipt or proof of purchase.
</p>

app/views/home/_term.html.erb
<div class="modal fade term" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4><%= t "terms.#{term}" %></h4>
      </div>
      <div id="price_modal_form_container" class="modal-body" style="padding-top: 10px;">
        <div class="single-item">
          <%= render partial:"home/#{term}" %>
        </div>
      </div>
      <div class="modal-footer" style="margin-top: 0px;">
        <button type="button" class="btn btn-primary" data-dismiss="modal">
          <i class='glyphicon glyphicon glyphicon-remove'></i>
          <%= t 'links.close' %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<% content_for :banner, 'about' %>
<% content_for :page_title, 'About' %>
<% content_for :page_description, 'Little Cs' %>
<% content_for :page_keywords, 'Pizza' %>

<% content_for :breadcrumb do %>
  <%= tb_breadcrumb 'About' %>
<% end %>

<!-- About company -->
<div class="about-company padd">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <!-- About Compnay Item -->
        <div class="row">         
        </div>
        <br >

          <div class="col-md-12 col-sm-12 col-xs-12">
          	<iframe src="//player.vimeo.com/video/46218719" class="about-iframe" width="800" height="600" align="center" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
          </div>
        </div>
        <div class="row about-company-item">
          <div class="col-md-6 col-sm-6 col-xs-6">
            <!-- About company inner items -->
            <div class="about-company-inner">
              <!-- Paragraph with icon -->
              <span class="company-feature"><i class="fa fa-building-o br-red"></i>
                <b class="red">2</b> Locations
              </span>
            </div>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-6">
            <!-- About company inner items -->
            <div class="about-company-inner">
              <!-- Paragraph with icon -->
              <span class="company-feature">
                <i class="fa fa-trophy br-lblue"></i>
                <b class="lblue">(*)</b> Awards
              </span>
            </div>
          </div>
          <div class="clearfix visible-xs"></div>
          <div class="col-md-6 col-sm-6 col-xs-6">
            <!-- About company inner items -->
            <div class="about-company-inner">
              <!-- Paragraph with icon -->
              <span class="company-feature">
                <i class="fa fa-users br-green"></i>
                <b class="green">8</b> Masters
              </span>
            </div>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-6">
            <!-- About company inner items -->
            <div class="about-company-inner">
              <!-- Paragraph with icon -->
              <span class="company-feature">
                <i class="fa fa-shopping-cart br-purple"></i>
                <b class="purple">98</b> Dishes
              </span>
            </div>
          </div>
        </div>
      </div>

     
    </div>
  </div>
</div>

<% if @chefs.any? %>
  <!-- Chefs Start -->
  <div class="chefs padd">
    <div class="container">
      <!-- Default Heading -->
      <div class="default-heading">
        <!-- Heading -->
        <h2>Our Masters</h2>
        <!-- Paragraph -->
        <p>
          Our fantastic team will do the best for you. Making sure you feel home while enjoying and experimenting our delicious menu!!!
        </p>
      </div>
      <div class="row">
        <% @chefs.each do |chef| %>
          <div class="col-md-4 col-sm-4">
            <!-- Chef Member -->
            <div class="chefs-member">
              <!-- Chefs member header -->
              <div class="chefs-head">
                <!-- Member background image -->
                <%= image_tag chef.background.url(:large), class: 'chefs-back img-responsive', alt: chef.name %>
                <!-- chef member image -->
                <%= image_tag chef.avatar.url(:large), class: 'chefs-img img-responsive', alt: chef.name %>
              </div>
              <!--Name / Heading -->
              <h3> <%= chef.name %> </h3>
              <!-- Member designation -->
              <span> <%= chef.position %> </span>
              <!-- Social media links -->
              <div class="social">

                <%= link_to chef.facebook, class:'facebook', target:'_blank' do %>
                  <i class="fa fa-facebook"></i>
                <% end unless chef.facebook.nil? %>

                <%= link_to chef.plus, class:'google-plus', target:'_blank' do %>
                  <i class="fa fa-google-plus"></i>
                <% end unless chef.plus.nil? %>

                <%= link_to chef.twitter, class:'twitter', target:'_blank' do %>
                  <i class="fa fa-twitter"></i>
                <% end unless chef.twitter.nil? %>

                <%= link_to chef.pinterest, class:'pinterest', target:'_blank' do %>
                  <i class="fa fa-pinterest"></i>
                <% end unless chef.pinterest.nil? %>

              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <!-- Chefs End -->
<% end %>

<div class="row">
  <div class="col-md-12 col-sm-12" style="text-align:center; color: #9a9a9a">
    ABN: 75 603 853 925
  </div>
</div>

app/views/home/category.html.erb
<% content_for :page_title, @category.name %>
<% content_for :page_description, 'Choose your pizza!' %>
<% content_for :page_keywords, @category.name %>

<% content_for :breadcrumb do %>
  <%= tb_breadcrumb 'Shopping' %>
<% end %>

<!-- Shopping Start -->
<div class="shopping">
  <div class="container">
    <!-- Shopping items content -->
    <div class="shopping-content">
      <%= render partial:'category', locals:{category:@category} %>
    </div>
  </div>
</div><!-- Shopping End -->

app/views/home/gallery.html.erb
<% content_for :page_title, 'Gallery' %>

<% content_for :breadcrumb do %>
  <%= tb_breadcrumb 'Gallery' %>
<% end %>

<!-- Shopping Start -->
<div class="shopping">
  <div class="container">
    <!-- Shopping items content -->
    <div class="shopping-content">
      <div class="row">
        <% Product.pizzas.each do |product| %>
          <div class="col-md-3 col-sm-6">
            <!-- Shopping items -->
            <div class="shopping-item">
              <!-- Image -->
              <%= link_to home_product_path(product.id, product.name.parameterize) do %>
                <%= image_tag product.photo.url(:large), class: 'img-responsive' %>
              <% end %>
              <!-- Shopping item name / Heading -->
              <h4 class="pull-left">
                <a href="item-single.html">
                  <%= product.name %>
                </a>
              </h4>
              <span class="item-price pull-right">
                <%= number_to_currency product.prices[0].value %>
              </span>
              <div class="clearfix"></div>
              <!-- Paragraph -->
              <p><%= product.items_friendly 30 %></p>
              <!-- Buy now button -->
              <div class="visible-xs">
                  <a class="btn btn-danger btn-sm" href="#">Buy Now</a>
              </div>
              <!-- Shopping item hover block & link -->
              <div class="item-hover br-red hidden-xs"></div>
                <% if customer_signed_in? %>
                  <%= link_to t('links.add_to', model_name:Cart.model_name.human),
                      cart_new_item_path(product.id),
                      remote: true, class:"link hidden-xs add_to_cart" %>
                <% else %>
                  <%= link_to t('links.add_to', model_name:Cart.model_name.human),
                        new_customer_registration_path, class:"link hidden-xs" %>
                <% end %>
              <span class="hot-tag br-red">Hot</span>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div><!-- Shopping End -->

app/views/home/menu.html.erb
<% content_for :banner, 'menu' %>
<% content_for :page_title, 'Menu' %>
<% content_for :page_description, 'Choose your pizza!' %>
<% content_for :page_keywords, 'Menu' %>

<% content_for :breadcrumb do %>
  <%= tb_breadcrumb 'Menu' %>
<% end %>

<div class="gallery">
  <div class="container">

    <!-- Gallery elements with pretty photo -->
    <div class="gallery-content">

      <ul class="nav nav-pills" data-active="<%= params[:active] %>">
        <% @categories.each_with_index do |category, index| %>
          <li class="<%= 'active' if is_tab_active(category, params[:active], index) %>">
            <a href="#<%= category.to_param %>" data-toggle="pill"><%= category.name %></a>
          </li>
        <% end %>
      </ul>

      <!-- Tab panes -->
      <div class="tab-content">
        <% @categories.each_with_index do |category, categoryIndex| %>
          <div class="tab-pane fade<%= ' in active' if is_tab_active(category, params[:active], categoryIndex) %>" id="<%= category.to_param %>">
            <br>
            <div class="row">
              <% category.products.shoppable.each_with_index do |product, productIndex| %>
                <div class="col-md-3 col-sm-4">
                  <!-- Separate gallery element -->
                  <div class="element">
                  	<span id="productNameSpan">
						<%= product.name %>                  		
                  	</span>
                    <span id="productImageSpan">
	                    <!-- Image -->
	                    <%= image_tag product.photo.url(:medium), class: 'img-responsive img-thumbnail', alt:product.name %>
	                    
	                    <!-- Gallery Image Hover Effect -->
	                    <span class="gallery-img-hover"></span>
	                    
	                    <!-- Gallery Image Hover Icon -->
	                    <a id="category<%= category.id %>product<%= product.id %>"
	                      href="JavaScript:void(0);"
	                      data-category="<%= category.id %>"
	                      data-product-index="<%= productIndex %>"
	                      data-title="<%= product.name %>"
	                      data-description="<%= product.describe %>"
	                      data-url="<%= product.photo.url %>">
	                      
	                      <i class="fa fa-search-plus hover-icon icon-left unique"></i>
	                    </a>
					</span>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div><!-- Separate gallery element --><!--/ End Gallery content class -->
  </div>
</div>

app/views/home/order.html.erb
<% content_for :banner, 'order_online' %>
<% content_for :page_title, 'Order Online' %>
<% content_for :page_description, 'Choose your pizza!' %>
<% content_for :page_keywords, 'Pizza' %>

<% content_for :breadcrumb do %>
  <%= tb_breadcrumb 'Order Online' %>
<% end %>

<!-- Shopping Start -->
<div class="shopping" style="margin-top: 40px;">
  <div class="container">
    <!-- Shopping items content -->
    <div class="shopping-content">

      <ul class="nav nav-pills">
        <% Category.with_shoppable_products.each_with_index do |category, index| %>
          <li class="<%= 'active' if index == 0 %>">
            <a href="#<%= category.to_param %>" data-toggle="pill"><%= category.name %></a>
          </li>
        <% end %>
      </ul>

      <!-- Tab panes -->
      <div class="tab-content">
        <% Category.with_shoppable_products.each_with_index do |category, index| %>
          <div class="tab-pane fade<%= ' in active' if index == 0 %>" id="<%= category.to_param %>">
            <br>
            <div class="row">
              <%= render partial:'category', locals:{category:category} %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div><!-- Shopping End -->

app/views/home/order_online.html.erb
<% content_for :banner, 'order_online' %>
<% content_for :page_title, 'Order Online' %>
<% content_for :page_description, 'Choose your pizza!' %>
<% content_for :page_keywords, 'Pizza' %>

<% content_for :breadcrumb do %>
  <%= tb_breadcrumb 'Order Online' %>
<% end %>

<!-- Shopping Start -->
<div class="shopping" style="margin-top: 40px;">
  <div class="container">
    <!-- Shopping items content -->
    <div class="shopping-content">

      <ul class="nav nav-pills">
        <% Category.with_shoppable_products.each_with_index do |category, index| %>
          <li class="<%= 'active' if index == 0 %>">
            <a href="#<%= category.to_param %>" data-toggle="pill"><%= category.name %></a>
          </li>
        <% end %>
      </ul>

      <!-- Tab panes -->
      <div class="tab-content">
        <% Category.with_shoppable_products.each_with_index do |category, index| %>
          <div class="tab-pane fade<%= ' in active' if index == 0 %>" id="<%= category.to_param %>">
            <br>
            <div class="row">
              <%= render partial:'category', locals:{category:category} %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div><!-- Shopping End -->

app/views/home/product.html.erb
<% content_for :banner, 'product' %>
<% content_for :page_title, @product.name %>
<% content_for :page_description, "#{@product.name}: #{@product.items_friendly}" %>
<% content_for :page_keywords, "#{@product.name},#{@product.items_friendly}" %>

<% content_for :breadcrumb do %>
  <%= tb_breadcrumb 'Order' %>
<% end %>

<!-- Single Item Start -->
<div class="single-item">
  <div class="container">
    <!-- Shopping single item contents -->
    <div class="single-item-content">
      <div class="row">
      	<div class="col-md-6 col-sm-6">
          <!-- Heading -->
          <h3><%= @product.name %></h3>
        </div>
        <div class="col-md-6 col-sm-6">
          <!-- Product image -->
          <%= image_tag @product.photo.url, class: 'img-responsive img-thumbnail' %>
        </div>
        <div class="col-md-6 col-sm-6">
          <div class="row">
            <div class="col-md-7 col-sm-12">
              <!-- Single item details -->
              <div class="item-details">
                <!-- Paragraph -->
                <p class="text-justify">
                  <%= @product.describe %>
                </p>
              </div>
            </div>
          </div><!--/ Inner row end  -->
          <%= link_to shopping_path, class:'btn btn-danger btn-sm' do %>
            <i class="glyphicon glyphicon-chevron-left"></i>
            Back
          <% end %>
          <%= add_to_cart_button @product %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Single Item End -->